[build]
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "netlify/pdf-templates/**",
    "netlify/keys/docusign_private.pem" # 👈 add this line
  ]


[functions."docusign-auth"]
  external_node_modules = ["node-fetch"]
