[build]
  command = "npm ci && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]
  included_files = [
    "netlify/pdf-templates/**",
    "netlify/keys/**"
  ]

[functions."docusign-auth"]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[functions."offers"]
  node_bundler = "esbuild"

[functions."proxy-units"]
  node_bundler = "esbuild"

[functions."send-for-signature"]
  node_bundler = "esbuild"

[functions."offer-pdf"]
  node_bundler = "esbuild"
  external_node_modules = [
    "@sparticuz/chromium",
    "puppeteer-core"
  ]
